version: '3.8'

services:

  db:
    container_name: recommendish-mongodb
    image: mongo
    # env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DATABASE_PASSWORD}
    volumes:
      - mongodb:/var/lib/recommendish/mongodb
    ports:
      - "${MONGODB_DATABASE_PORT}:${MONGODB_DATABASE_PORT}"
    expose:
      - "${MONGODB_DATABASE_PORT}"
    restart: unless-stopped
    networks:
      - backend

  node:
    container_name: recommendish-node
    depends_on:
      - db
    build: ./server
    restart: unless-stopped
    # env_file: .env
    environment:
      - CLIENT_PORT=$CLIENT_PORT
      - BASE_URL=$BASE_URL
      - PORT=$PORT
    ports:
      - "5004:5004"
    expose:
      - "5004"
    networks:
      - backend
      - frontend

  react:
    container_name: recommendish-react
    depends_on:
      - node
    build:
      context: ./client
    ports:
      - "3004:80"
    networks:
      - frontend

volumes:
  mongodb:


networks:
  backend:
  frontend:
