version: '3.8'

services:

  db:
    container_name: recommendish-mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DATABASE_PASSWORD}
    volumes:
      - mongodb:/var/lib/recommendish/mongodb
    ports:
      - "${MONGODB_DATABASE_PORT}:27017"
    expose:
      - "${MONGODB_DATABASE_PORT}"
    restart: unless-stopped
    networks:
      - backend

  node:
    container_name: recommendish-node
    depends_on:
      - db
    image: harpica/recommendish-node:latest
    restart: unless-stopped
    environment:
      - BASE_URL=$BASE_URL
      - SERVER_URL=$SERVER_URL
      - SERVER_PORT_INTERNAL=$SERVER_PORT_INTERNAL
      - MONGODB_DATABASE_USERNAME=$MONGODB_DATABASE_USERNAME
      - MONGODB_DATABASE_PASSWORD=$MONGODB_DATABASE_PASSWORD
      - MONGODB_DATABASE_NAME=$MONGODB_DATABASE_NAME
      - JWT_KEY=$JWT_KEY
      - SOCIALS_GITHUB_ID=$SOCIALS_GITHUB_ID
      - SOCIALS_GITHUB_SECRET=$SOCIALS_GITHUB_SECRET
      - SOCIALS_VK_ID=$SOCIALS_VK_ID
      - SOCIALS_VK_SECRET=$SOCIALS_VK_SECRET
      - SOCIALS_TWITTER_APP_KEY=$SOCIALS_TWITTER_APP_KEY
      - SOCIALS_TWITTER_APP_KEY_SECRET=$SOCIALS_TWITTER_APP_KEY_SECRET
      # for OAuth 2.0
      - SOCIALS_TWITTER_ID=$SOCIALS_TWITTER_ID
      - SOCIALS_TWITTER_SECRET=$SOCIALS_TWITTER_SECRET
      - CLOUD_NAME=$CLOUD_NAME
      - CLOUD_KEY=$CLOUD_KEY
      - CLOUD_SECRET=$CLOUD_SECRET
    ports:
      - "${SERVER_PORT_INTERNAL}:${SERVER_PORT_INTERNAL}"
    expose:
      - "${SERVER_PORT_INTERNAL}"
    volumes:
      - /etc/ssl/ssl_certs_porkbun:/etc/ssl/ssl_certs_porkbun:ro
    networks:
      - backend
      - frontend

  react:
    container_name: recommendish-react
    image: harpica/recommendish-react:latest
    depends_on:
      - node
    ports:
      - "${CLIENT_PORT_INTERNAL}:80"
    networks:
      - frontend

volumes:
  mongodb:


networks:
  backend:
  frontend:
